### ISSUE TITLE
Feature: Middle Tier serving REST API to perform CRUD operations on the Data Tier and return JSON response to a request

### ISSUE THREAD

**Issue by MichaelKoiku** [MichaelKoiku/Campus-Feed#2]
# Epic Title

Feature: Middle Tier serving REST API to perform CRUD operations on the Data Tier and return JSON response to a request

## Epic Description
This feature will provide a middle tier and data tier. The front tier (client) will be able to send requests using the REST API provided by the middle tier to perform CRUD operations or other complex operations on the data tier and receive a JSON response to be displayed according to the front tier design

## List of Tasks (Complete in order)

- [x] [Task 1: Provision an Amazon RDS database instance](https://github.com/MichaelKoiku/Campus-Feed/issues/1)
- [x] [Task 2: Implement a REST API with Spring Boot Server with CRUD functionality](https://github.com/MichaelKoiku/Campus-Feed/issues/3)
- [ ] [Task 3: Add Authentication and Authorization to the middle tier](https://github.com/MichaelKoiku/Campus-Feed/issues/4)
